In [2]:
from flask import Flask, render_template,request,jsonify
from flask_cors import CORS,cross_origin
import requests
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen as uReq
import pandas as pd

In [13]:
df1 = pd.read_excel(r"C:\\Users\\Vishal\\Downloads\\test.xlsx",engine = 'openpyxl',sheet_name='Sheet2')

In [14]:
df1

             sku
0   184471250300
1   282258534631
2   384670123883
3   154511344772
4   184510234154
..           ...
94  254112916571
95  282821856235
96  131284945633
97  254478190034
98  253260356059

[99 rows x 1 columns]

In [32]:
df={}
l=[]
s=[]
for i in df1['sku']:
    ebay_url="https://www.ebay.com.au/itm/"+ str(i)
    prodRes= requests.get(ebay_url)
    prodRes.encoding='utf-8'
    prod_html = bs(prodRes.text,'html.parser')
    #print(prod_html)
    try:
        spec=prod_html.find('div',{'data-testid':"ux-layout-section__item", 'class':"ux-layout-section__item ux-layout-section__item--table-view"}).text
    except:
        pass
    t=''
    
    
    if 'Brand:' in spec:
        spec.find('Brand:')
        t=spec[spec.find('Brand:'):spec.find('Brand:')+50]
        a=t[6:]
        if ":" not in a:
            l.append(i)
            s.append(a)
            print(i,a)
        else:
            k=' '.join(a[:a.find(':')].split(' ')[:-1])
            l.append(i)
            s.append(k)
            print(i,k)
        
    
    else:
        pass
df['asin']=l
df['brand']=s

184471250300 Unbranded
282258534631 Hi Lift
384670123883 unbranded
154511344772 Unbranded
184510234154 Unbranded
221394216715 Magic Wand
174594149539 Aloe Vera Australia Skin
223729921600 Victoria's Secret
324988753794 asap UVA
224655477229 Victoria's Secret
124443598237 Marhaba
124443591794 Marhaba
272289421333 Baraka
353683602824 Saltylicious
185274958478 Adairs
152652421496 DAISO
271628819292 G.R.E.E.N.
393399502940 Unbranded
271777062686 GREEN HEMP Active
184691855588 Unbranded
373008470619 Jurlique Body
233202307246 Herbal.remedies
175118784135 Life Extension
161008572843 CeraVe
154799231130 Unbranded
284612470800 Unbranded
194680939472 Unbranded
264777150222 Unbranded
224334438902 unbranded
222404521267 ISABEL RICARDO UVA
224002221942 Unbranded
154511234523 Unbranded
284275070362 purelyBlack
313566473530 Unbranded
254081221300 MILDTOUCH Suitable
224442013269 Disa
224657352774 Lanthome
382246017678 Madina Skin
174612892351 My Natural Beauty
174612891813 My Natural Beauty
185239370310 Bath & Body Works
185275066791 Bath & Body Works
224814298469 Bath & Body Works
304266815721 Unbranded
115086446691 Nearly Natural
133587587004 Hydraderm
133193731385 Tangle Teezer
133483952157 The Hemp Worx
133501595063 The Hemp Worx
133483965297 The Hemp Worx
392936242575 Handmade
392937188376 Unbranded
324438985469 LipSense
334315040682 MILK AND HONEY Size
334312791240 Lush
334312761119 Lush
284635800350 100% Pure
194202460424 100% Pure
402897412031 purelyBlack
183661308786 RAMOSU UVA
234121217716 ACNE FELDIN Main
265291735612 ACNE FELDIN
255051058888 AXIS-Y
254273162654 Benton
253222434297 Benton Body
363640771478 PHATOIL Bundle
312113371755 Christian Dean Body
312113366347 Christian Dean Body
403401349049 Palette
234354377078 CLIO
234354373518 CLIO
252543520902 COSRX
252819204050 COSRX Body
265273361116 DEWI SRI SPA
274490674767 DR.JART+
265147663651 ENCHANTEUR
334141799233 ERHA Main
265311424612 ERHA
282764478656 Etude House Skin
194056166936 PELICAN UVA
194026402354 PELICAN UVA
194056098289 PELICAN UVA
194026402319 Mentholatum UVA
233262225544 Goodal Body
265296274292 HERBORIST
154582274163 HOLIKA HOLIKA Country/Region of
253670499836 Holika Holika Skin
154330996602 Unbranded
164659957739 Unbranded
254112916571 KLAIRS
282821856235 purelyblack UVA
131284945633 Nature Republic Skin
254478190034 Nature Republic
253260356059 Nature Republic

In [33]:
sd=pd.DataFrame(df)

In [34]:
sd

            asin                 brand
0   184471250300             Unbranded
1   282258534631               Hi Lift
2   384670123883             unbranded
3   154511344772             Unbranded
4   184510234154             Unbranded
..           ...                   ...
89  254112916571                KLAIRS
90  282821856235       purelyblack UVA
91  131284945633  Nature Republic Skin
92  254478190034       Nature Republic
93  253260356059       Nature Republic

[94 rows x 2 columns]